# Generated by Django 3.1.2 on 2020-12-27 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerFlag',
        ),
    ]
